[[grimblast-git]]
url = "https://github.com/hyprwm/contrib.git"
commit = "65d42dcbfde2229a75ccdb195c318dfe241f9ade"

[[oh-my-zsh-git]]
url = "https://github.com/ohmyzsh/ohmyzsh.git"
commit = "3b5f018f7025a347e4888408b566caeaef2fabd7"

[[pokemon-colorscripts-git]]
url = "https://gitlab.com/phoneybadger/pokemon-colorscripts.git"
commit = "0483c85b93362637bdd0632056ff986c07f30868"

[[rofi-emoji-git]]
url = "https://github.com/Mange/rofi-emoji"
commit = "09c7358ad98a95e331f6d0a124626e754149049d"

[[rofi-lbonn-wayland-git]]
url = "https://github.com/lbonn/rofi.git"
branch = "wayland"
commit = "d88b475bad26a6ba60c85cd7830e441da5774cdb"

[[rofi-lbonn-wayland-git]]
url = "https://github.com/sardemff7/libgwater.git"
commit = "d86f9903efb9c490c0e3b0316d7f2da5b5a5632c"

[[rofi-lbonn-wayland-git]]
url = "https://github.com/sardemff7/libnkutils.git"
commit = "3d71d89eb9690104d55ca1d0cad4c5b63850895d"

[[swaylock-effects-git]]
url = "https://github.com/jirutka/swaylock-effects.git"
commit = "496059a8565c2d5eed672c2e5bc5e1edd14b3de8"

[[zsh-theme-powerlevel10k-git]]
url = "https://github.com/romkatv/powerlevel10k.git"
commit = "2b7da93df04acd04d84f5de827e5b14077839a4b"
